Unit converter
sadanandpai/frontend-mini-challenges pull request #133
Opened 2023-10-08 07:23 UTC by apu52

# Title and Issue number 

Title : Unit Converter

Issue No. : #130 

Code Stack : HTML, CSS ,JS

Close #130 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

2023-10-08 07:24 UTC, apu52 commented
@sadanandpai Please take a review of my PR & please merge it.

2023-10-09 05:44 UTC, sadanandpai requested changes

2023-10-09 05:44 UTC, sadanandpai commented on native/helpers/challenges.js
> +    link: 'https://65072ad6fbb37b52ebcf0b6c--radiant-macaron-33a884.netlify.app/#',
The link should be to the challenge in the repo only

2023-10-09 05:44 UTC, sadanandpai commented on native/helpers/challenges.js
> +    link: 'https://apu52.github.io/Unit-converter/',
The link should be to the challenge in the repo only

2023-10-09 05:44 UTC, sadanandpai commented on native/machine-coding/Unit converter/Contributing.md
why do we have this file

2023-10-09 05:44 UTC, sadanandpai commented on native/machine-coding/Unit converter/Contributors.md
why do we have this file

2023-10-09 05:44 UTC, sadanandpai commented on native/machine-coding/Unit converter/README.md
> +iii)JS
Please keep a valid description for users to understand about the project

2023-10-09 05:44 UTC, sadanandpai commented on native/machine-coding/Unit converter/index.html
> +    <link rel="stylesheet" href="style.css" />
please include the required tags

2023-10-09 05:44 UTC, sadanandpai commented on native/machine-coding/Unit converter/index.js
> +var inch = document.getElementById("inch");
use const

2023-10-09 05:44 UTC, sadanandpai commented on native/machine-coding/Unit converter/style.css
> +  }
do not modify font family

2023-10-10 04:12 UTC, apu52 commented
@sadanandpai I have resolved the conflicts...Can you please take a look & please merge it

2023-10-10 04:19 UTC, apu52 commented
I have deleted those files & have changed the codes . @sadanandpai Can you please take a review & please merge it

2023-10-10 18:08 UTC, sadanandpai commented
@apu52 please address the comments properly. Do not mark resolved without fixing.

2023-10-11 04:19 UTC, sadanandpai requested changes

2023-10-28 17:34 UTC, closed without merging