Added Infinite scroll in native js
sadanandpai/frontend-mini-challenges pull request #140
Opened 2023-10-08 16:08 UTC by srijanB7

# Title and Issue number 

Title : Added the code for Infinite scrolling in native js.

Issue No. : Not an issue

Code Stack : HTML, CSS, JS

# Checklist:

- [] I have solved the infinite-scrolling problem in native JS.
- [] I have commented my code, particularly in hard-to-understand areas

2023-10-11 04:20 UTC, sadanandpai requested changes

2023-10-11 04:20 UTC, sadanandpai commented on native/machine-coding/infinite-scroll/index.html
> +    <link rel="stylesheet" href="style.css" />
import the header as done in [counter](https://github.com/sadanandpai/frontend-mini-challenges/blob/main/native/machine-coding/counter/index.html)

Also, remove the other tags

2023-10-11 04:20 UTC, sadanandpai commented on native/machine-coding/infinite-scroll/style.css
> +@import url(../../helpers/core.css);
can get rid of this as header will have it as per the new changes

2023-10-11 04:20 UTC, sadanandpai commented on native/helpers/challenges.js
> +    difficulty: 'hard',
can be moved to medium

2023-10-11 06:23 UTC, srijanB7 commented
Made the assigned changes.

2023-10-16 06:57 UTC, srijanB7 commented
@sadanandpai I have made the changes.

2023-10-16 12:49 UTC, sadanandpai commented
@srijanB7 All comments are not yet addressed. 

Have you run the app in local once?

2023-10-16 17:27 UTC, srijanB7 commented
@sadanandpai I did run it locally. While debugging in one of the commits I left the core css import by mistake. Turns out I was importing the wrong header file( navbar.js instead of header.js  🥲 ). 

Now I have fixed it. Sorry for the inconvenience.

2023-10-17 13:36 UTC, sadanandpai approved these changes

2023-10-17 13:38 UTC, merged