Add a Music Kit App #137
sadanandpai/frontend-mini-challenges pull request #176
Opened 2023-10-10 12:52 UTC by shivam200446

# Title and Issue number 

Title : Add a Music Kit App

Issue No. : #137 

Code Stack :  HTML, CSS , JAVASCRIPT 

Close #137

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have updated the Index.html file for my contribution

2023-10-10 13:05 UTC, sadanandpai commented
Please follow the standards mentioned in contributing.md along with coding standards of ES6 and quality code

2023-10-10 13:06 UTC, sadanandpai requested changes
Please follow the standards mentioned in contributing.md along with coding standards of ES6 and quality code

2023-10-11 06:07 UTC, sadanandpai requested changes

2023-10-11 06:07 UTC, sadanandpai commented on native/machine-coding/Music Kit/kit.html
> +  <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
import the header as done in [counter](https://github.com/sadanandpai/frontend-mini-challenges/blob/main/native/machine-coding/counter/index.html)

Also, remove the other tags

2023-10-11 06:07 UTC, sadanandpai commented on native/machine-coding/Music Kit/kit.html
> +    <button class="l drum">l</button>
can we populate from js

2023-10-11 06:07 UTC, sadanandpai commented on native/machine-coding/Music Kit/musickit.js
> +}
follow coding standards

2023-10-11 06:07 UTC, sadanandpai commented on native/machine-coding/Music Kit/styles.css
> +}
not needed

2023-10-11 06:07 UTC, sadanandpai commented on native/machine-coding/Music Kit/styles.css
> +}
dont add font family

2023-10-11 16:24 UTC, shivam200446 reviewed
@sadanandpai  I have made all the changes you asked for. Thanks for the Guidance and instruction Bhaiya.

2023-10-11 16:56 UTC, arpansaha13 commented on native/machine-coding/Music Kit/musickit.js
> +for (const i = 0; i < numberOfDrumButtons; i++) {
Check if this for loop is running normally or not. Since this variable is const I doubt if i++ will work or not.

2023-10-11 17:10 UTC, shivam200446 reviewed
@arpansaha13 Yes bhaiya Const was not working in the loop. I have changed it to let now it's all working. Thanks you..

2023-10-11 17:12 UTC, arpansaha13 commented
Nice 😊

2023-10-11 18:02 UTC, sadanandpai commented
The challenge has to be added to the challenges list for it to appear in the UI @shivam200446

2023-10-12 14:42 UTC, shivam200446 commented
@sadanandpai Bhaiya Updated the challenges.js

2023-10-12 15:14 UTC, arpansaha13 commented on native/helpers/challenges.js
It says there are merge conflicts in this file. Please take a pull from the main branch and resolve he mege conflicts. If you face problems you can send a screenshot here.

2023-10-12 16:23 UTC, shivam200446 commented
@arpansaha13 @sadanandpai I have created a pull request with main branch (PR #213) with all changes. Please look at that!

2023-10-12 16:51 UTC, closed without merging