Add a Dice game #138
sadanandpai/frontend-mini-challenges pull request #177
Opened 2023-10-10 13:10 UTC by shivam200446

# Title and Issue number 

Title : Add a Dice game

Issue No. : #138

Code Stack: HTML, CSS , HTML

Close #138

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have updated the Index.html file for my contribution

2023-10-11 04:17 UTC, sadanandpai requested changes

2023-10-11 04:17 UTC, sadanandpai commented on native/machine-coding/Dice Game/dice.js
> +var image2 = document.querySelectorAll("img")[1].setAttribute("src", imgsource2);
use const or let

2023-10-11 04:17 UTC, sadanandpai commented on native/machine-coding/Dice Game/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Lobster" rel="stylesheet">
import the header as done in [counter](https://github.com/sadanandpai/frontend-mini-challenges/blob/main/native/machine-coding/counter/index.html)

Also, remove the other tags

2023-10-11 04:17 UTC, sadanandpai commented on native/machine-coding/Dice Game/styles.css
> +}
dont modify font-family, margin, padding

2023-10-11 16:48 UTC, shivam200446 reviewed
@sadanandpai I have made all the changes you asked for. Thank you soo much for the Guidance and instruction.

2023-10-11 18:03 UTC, sadanandpai commented
The challenge has to be added to the challenges list for it to appear in the UI @shivam200446

2023-10-11 18:28 UTC, shivam200446 commented
> The challenge has to be added to the challenges list for it to appear in the UI @shivam200446

How do it?

2023-10-12 03:36 UTC, sadanandpai commented
Please refer to the contributing.md and other challenges

2023-10-12 14:38 UTC, shivam200446 commented
@sadanandpai Updated challenges.js please check it once.

2023-10-12 16:57 UTC, shivam200446 commented
Bhaiya, why it is showing conflict

2023-10-12 17:18 UTC, sadanandpai requested changes

2023-10-12 17:18 UTC, sadanandpai commented on native/helpers/challenges.js
> +    developer: 'shivam200446',
add your details to the contributors list also. Else name won't appear

2023-10-12 17:18 UTC, sadanandpai commented
conflicts are there. Rebase with latest changes

2023-10-12 18:27 UTC, shivam200446 commented
@sadanandpai Bhaiya, I have updated all the changes and solved the conflicts. please look at it. Thank you so much for all your help really learned a lot.

2023-10-13 03:29 UTC, sadanandpai approved these changes

2023-10-13 03:29 UTC, merged