[JS]: Light and dark mode
sadanandpai/frontend-mini-challenges pull request #178
Opened 2023-10-10 13:15 UTC by ankit071105

# Completd All the necessary changes and added Dark Mode Feature

2023-10-10 14:20 UTC, arpansaha13 commented
Please do not create a new PR after every review.
When you push a new commit to your branch they will automatically appear in this PR.
There is no need to create new PRs after every change.

2023-10-11 04:13 UTC, sadanandpai requested changes

2023-10-11 04:13 UTC, sadanandpai commented on index.html
is there a need for changing the file?

2023-10-11 04:13 UTC, sadanandpai commented on .DS_Store
why is this needed

2023-10-11 04:13 UTC, sadanandpai commented on vue/index.html
is there a need to change the file?

2023-10-11 04:13 UTC, sadanandpai commented on native/index.js
is there a need to change the file?

2023-10-11 04:13 UTC, sadanandpai commented on native/index.html
> +    </script>
please dont keep script in hmtl

2023-10-11 04:13 UTC, sadanandpai commented on native/index.html
> +
can we not do it without font awesome

2023-10-12 04:14 UTC, ankit071105 commented
> # Completd All the necessary changes and added Dark Mode Feature

changes done as per the requested and made a new separate javascript file

2023-10-13 17:40 UTC, sadanandpai approved these changes

2023-10-13 17:41 UTC, merged

2023-10-13 17:49 UTC, arpansaha13 commented on index.html
> +
I am not sure how that happened 🤔

2023-10-13 17:50 UTC, arpansaha13 commented on native/index.html
> +
Oh this one is a habit of mine 🥲