Fitness tracker
sadanandpai/frontend-mini-challenges pull request #218
Opened 2023-10-13 07:08 UTC by CrypticRevenger

# Title and Issue number 
Add Fitness Tracker #214 
Title : Add Fitness Tracker
Issue No. : #214

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have updated the Index.html file for my contribution

2023-10-13 07:11 UTC, CrypticRevenger commented
@sadanandpai sorry for the new PR, I did the same that you told but, a new PR is created. I apologize.
Thank you.

2023-10-13 13:41 UTC, arpansaha13 commented on native/helpers/challenges.js
> +    link: 'fitness-tracker',
This link is incorrect in the UI
Either make the link `fitness-tracker/tracker.html`, or rename the `tracker.html` file to `index.html`

2023-10-13 13:43 UTC, arpansaha13 commented on native/helpers/challenges.js
> +    link: 'fitness-tracker',
Also place the challenges with same difficulty together in the challenges list

2023-10-13 13:56 UTC, CrypticRevenger commented
@sadanandpai , @arpansaha13  All the changes are done as per your instructions.
Thank you.

2023-10-13 13:58 UTC, arpansaha13 reviewed
I think there is a problem probably with the CSS. Please open this file in your local and fix the navbar. Navbar should be on top like in other challenges.

2023-10-13 14:00 UTC, arpansaha13 commented on native/machine-coding/fitness-tracker/style.css
> +    align-items: center;
The navbar won't appear on screen properly due to flexbox in the body.

2023-10-13 14:12 UTC, arpansaha13 commented on native/machine-coding/fitness-tracker/index.html
> +            <button onclick="addWorkout()">Add</button>
Looks like none of the js functions are working. You may try using `addEventListener` in the script instead.

2023-10-13 14:27 UTC, CrypticRevenger commented
@arpansaha13 Fixed all the above problems.
Thank you.

2023-10-13 18:08 UTC, arpansaha13 commented
You should remove onclick handlers from html
All event listeners should be added from the script using addEventListener

2023-10-13 18:49 UTC, CrypticRevenger commented
@sadanandpai @arpansaha13 All the problems are fixed.
Thank you.

2023-10-14 06:53 UTC, sadanandpai requested changes

2023-10-14 06:53 UTC, sadanandpai commented on native/machine-coding/fitness-tracker/index.html
> +    <script src="index.js"></script>
move to head with defer attribute

2023-10-14 06:53 UTC, sadanandpai commented on native/machine-coding/fitness-tracker/index.js
> +document.addEventListener("DOMContentLoaded", function () {
wrapping in DOMContentLoaded listener is not needed when script is loaded with defer attirbute

2023-10-14 08:57 UTC, CrypticRevenger commented
@sadanandpai All the issues are fixed.
Thank you.

2023-10-14 16:45 UTC, merged