Movie-Info-App
sadanandpai/frontend-mini-challenges pull request #225
Opened 2023-10-13 17:46 UTC by AckermanLevi1

# Title and Issue number 

Title :

Issue No. :#215

Code Stack : HTML, CSS, JAVASCRIPT

Close #<215>

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the Index.html file for my contribution

<h1>Website Link</h1>
<a href="https://moviestadka.netlify.app/">Click here</a>

2023-10-13 17:54 UTC, arpansaha13 commented
You do not need to create a new PR after every change
When you push a new commit in your branch (same branchfrom where PR was created) they will automatically appear here

2023-10-13 17:58 UTC, sadanandpai requested changes

2023-10-13 17:58 UTC, sadanandpai commented on native/machine-coding/Movie-Info-App/index.css
> +    font-family: Arial, sans-serif;
dont add any font-family

2023-10-13 17:58 UTC, sadanandpai commented on native/machine-coding/Movie-Info-App/index.html
> +    <title>Movie Info Website</title>
only these are enough in head

```
<script src="./index.js" defer></script>
<script src="../../helpers/header.js" type="module"></script>
<link rel="stylesheet" href="./index.css">
```

2023-10-13 17:58 UTC, sadanandpai commented on native/machine-coding/Movie-Info-App/index.js
> +document.addEventListener('DOMContentLoaded', function() {
as defer is used while loading script, I don't think we need the DOMContentLoaded listener. Can be written directly

2023-10-13 17:58 UTC, sadanandpai commented on native/machine-coding/Movie-Info-App/index.js
> +                const moviePoster = document.getElementById('movie-poster');
can we not move these query selectors outside to the top of file and use the variables inside

2023-10-13 17:58 UTC, sadanandpai commented on native/machine-coding/Movie-Info-App/index.js
> +        const apiKey = 'adff2bf8';
move to the top of file

2023-10-13 17:58 UTC, sadanandpai commented on native/machine-coding/Movie-Info-App/index.js
> +                moviePoster.src = data.Poster;
can we move the assignment task to a separate function and keep the fetch lean for readability

2023-10-13 17:58 UTC, sadanandpai commented on native/helpers/challenges.js
name the folder in small case only. (can omit **app**)

movie-Info

2023-10-13 21:07 UTC, AckermanLevi1 commented
@sadanandpai pls check

2023-10-14 06:51 UTC, sadanandpai requested changes

2023-10-14 06:51 UTC, sadanandpai commented on native/helpers/challenges.js
> +    link: 'Movie-Info-App',
`link: 'movie-info'`

should be same as folder name

2023-10-14 06:51 UTC, sadanandpai commented on native/machine-coding/movie-info/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
above meta tags not needed

2023-10-14 08:09 UTC, AckermanLevi1 commented
@sadanandpai pls check

2023-10-14 16:59 UTC, sadanandpai commented
@AckermanLevi1 

Not handled for invalid movie
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/01cd7af8-30d2-49d4-a361-27352f5e677e)

Also pressing enter is not working after entering movie name. 

Please work on those

2023-10-15 06:31 UTC, closed without merging