Color Mixer
sadanandpai/frontend-mini-challenges pull request #227
Opened 2023-10-13 18:54 UTC by Sumitwarrior7

# Title and Issue number 

Title :Color Mixer

Issue No. :#226

Code Stack : React

Close #226

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

2023-10-14 04:21 UTC, sadanandpai requested changes

2023-10-14 04:21 UTC, sadanandpai commented on react/src/machine-coding/color-mixer/index.jsx
> +import './styles.module.css';
only scoped imports are allowed. Follow the other challenges

2023-10-14 04:21 UTC, sadanandpai commented on react/src/machine-coding/color-mixer/index.jsx
> +  };
why can't move this function out of the component by passing the colors as arguments

2023-10-19 19:13 UTC, Sumitwarrior7 commented
The changes you have specified are done

2023-10-22 08:18 UTC, Sumitwarrior7 commented
@sadanandpai please review the changes
i have some more prs waiting for this project

2023-10-22 13:47 UTC, sadanandpai approved these changes

2023-10-22 13:47 UTC, sadanandpai commented
Please fix the conflicts

2023-10-22 16:17 UTC, Sumitwarrior7 commented
@sadanandpai Conflicts fixed

2023-10-23 17:48 UTC, merged