add: qr scanner and generator
sadanandpai/frontend-mini-challenges pull request #258
Opened 2023-10-16 17:01 UTC by singodiyashubham87

# Title and Issue number 

Title : QR Scanner and Generator

Issue No. : #249 

Code Stack : HTML, CSS, JS

Close #<issue_no>

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the Index.html file for my contribution

2023-10-17 13:29 UTC, sadanandpai requested changes

2023-10-17 13:29 UTC, sadanandpai commented on native/machine-coding/qr-scanner-and-generator/images/bg.jpg
no bg images are required

2023-10-17 13:29 UTC, sadanandpai commented on native/machine-coding/qr-scanner-and-generator/index.html
> +    ></script>
bootstrap is not needed

2023-10-17 13:29 UTC, sadanandpai commented on native/machine-coding/qr-scanner-and-generator/scripts/html5-qrcode.min.js
lets import from cdn and not add it in codebase

2023-10-17 13:29 UTC, sadanandpai commented on native/machine-coding/qr-scanner-and-generator/scripts/qrcode.js
> +}));
use the modern standards. Also, divide the file into multiple reusable chunks

2023-10-17 13:29 UTC, sadanandpai commented on native/machine-coding/qr-scanner-and-generator/styles/styles.css
> +@import url("https://fonts.googleapis.com/css2?family=Ysabeau+Infant&display=swap");
no new font needed

2023-10-17 13:29 UTC, sadanandpai commented on native/machine-coding/qr-scanner-and-generator/styles/styles.css
> +}
above css rules are not needed

2023-10-17 13:38 UTC, singodiyashubham87 commented
@sadanandpai Have a look now.

2023-10-17 16:55 UTC, sadanandpai requested changes

2023-10-17 16:56 UTC, sadanandpai commented
Please address all the comments

2023-10-18 01:01 UTC, singodiyashubham87 commented
@sadanandpai Done!

2023-10-18 16:54 UTC, sadanandpai requested changes

2023-10-18 16:54 UTC, sadanandpai commented on native/machine-coding/qr-scanner-and-generator/scripts/html5-qrcode.min.js
external library file should not be copied to the repo. Please import if cdn link is present

2023-10-26 04:23 UTC, closed without merging