Add atm-simulator
sadanandpai/frontend-mini-challenges pull request #267
Opened 2023-10-18 15:28 UTC by Bratajit-03

# Title

Title : ATM-Simulator

Code Stack : HTML,CSS and Javascript

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

2023-10-18 15:44 UTC, arpansaha13 commented
Please do not create a new PR after every review or change.
The review can continue in the same PR even after adding new commits.

2023-10-19 06:23 UTC, Bratajit-03 commented
@arpansaha13 sir, i apologise.please kindly review my PR.

2023-10-22 13:49 UTC, sadanandpai commented
Do not add more than 1 challenge in the PR. Please keep this only for ATM Simulator

2023-10-23 06:42 UTC, Bratajit-03 commented
@sadanandpai sir, i have done the required changes.please review it.

2023-10-23 13:48 UTC, arpansaha13 requested changes

2023-10-23 13:48 UTC, arpansaha13 commented on native/machine-coding/atm-simulator/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
These lines can be removed

2023-10-23 13:48 UTC, arpansaha13 commented on native/machine-coding/atm-simulator/index.html
> +    <script src="../../helpers/navbar.js" type="module"></script>
It should be `../../helpers/header.js` and not `../../helpers/navbar.js`.

2023-10-23 13:48 UTC, arpansaha13 commented on native/machine-coding/atm-simulator/index.html
> +            <button onclick="logout()">Logout</button>
Use `click` **event listeners** in your script file instead of using `onclick` in HTML

2023-10-23 13:48 UTC, arpansaha13 commented on native/machine-coding/atm-simulator/styles.css
> +}
Body styles can be removed. Applying flex on body will not render the navbar properly I guess. **Do test in your local**.

2023-10-24 07:28 UTC, Bratajit-03 commented
@arpansaha13 sir, i have resolved all the issues, please kindly check it.

2023-10-24 11:30 UTC, merged