Your Sport is added
sadanandpai/frontend-mini-challenges pull request #291
Opened 2023-10-23 19:48 UTC by Sumitwarrior7

# Title and Issue number 

Title :Your Sport

Issue No. :#290

Code Stack : React

Close #290

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have updated the Index.html file for my contribution

2023-10-24 03:32 UTC, sadanandpai requested changes

2023-10-24 03:32 UTC, sadanandpai commented on react/src/machine-coding/your-sport/index.jsx
> +import './styles.module.css';
only scoped imports

2023-10-24 03:32 UTC, sadanandpai commented on react/src/machine-coding/your-sport/styles.module.css
> +h1 {
direct tag modifiers not allowed

2023-10-24 03:32 UTC, sadanandpai commented on react/src/machine-coding/your-sport/styles.module.css
> +button {
direct tag modifiers not allowed

2023-10-24 03:32 UTC, sadanandpai commented on react/src/machine-coding/your-sport/index.jsx
> +const Sport = () => {
rename to YourSport

2023-10-25 05:43 UTC, Sumitwarrior7 commented
The changes have been done , now you can check and merge
@sadanandpai

2023-10-25 12:59 UTC, merged