Add TrafficLightChallenge
sadanandpai/frontend-mini-challenges pull request #324
Opened 2023-11-04 13:06 UTC by rishabhm05

# Title and Issue number 

Title : TrafficLightChallenge

Issue No. :

Code Stack :  React JS

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have updated the Index.html file for my contribution

2023-11-04 14:35 UTC, arpansaha13 requested changes
Consider showing a timer for how long the red and green lights will show

2023-11-04 14:35 UTC, arpansaha13 commented on react/src/helpers/challenges.ts
> +  ],
Put the new challenge along with the other medium difficulty challenges

2023-11-04 14:39 UTC, arpansaha13 requested changes

2023-11-04 14:39 UTC, arpansaha13 commented on react/src/machine-coding/traffic-light/App.jsx
> +        })}
Each item in list-rendering should have a unique `key` prop. Please add the `key` prop in the list elements.

Note that the `index` variable is unused. Please remove it if it is not required. Also, ideally, index should not be used as key.

2023-11-04 17:33 UTC, rishabhm05 commented
@arpansaha13  Hi  i have done required changes
1 . Added key for each light item
2. Displayed duration for Active Light
3 . Added challenge below the other medium challenges

2023-11-05 04:50 UTC, arpansaha13 approved these changes

2023-11-05 04:55 UTC, merged

2023-11-05 05:02 UTC, arpansaha13 commented
Thank you for your contribution!

2023-11-05 05:18 UTC, arpansaha13 commented
I have noticed a bug right now. Check out this issue #325.
Would you like to take it up?

2023-11-05 05:30 UTC, rishabhm05 commented
yes @arpansaha13  Please assign it to me.

2023-11-05 05:40 UTC, arpansaha13 commented
I am not able to add you as an assignee.
But you can open the PR for it anyway 👍

2023-11-05 05:41 UTC, rishabhm05 commented
okay sure