Added A calculator project
sadanandpai/frontend-mini-challenges pull request #369
Opened 2024-01-05 15:06 UTC by LIZA1608

# Title and Issue number 

Title :

Issue No. :

Code Stack : 

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have updated the Index.html file for my contribution

2024-01-05 15:12 UTC, LIZA1608 commented
please merge it

2024-01-06 04:13 UTC, sadanandpai requested changes

2024-01-06 04:13 UTC, sadanandpai commented on apps/react/src/challenges/calculator/calculator.module.css
> +}
do not modify the global styles

2024-01-06 04:13 UTC, sadanandpai commented on apps/react/src/challenges/calculator/App.jsx
> +                <button onClick={() => calculate()} className={styles.calculator__operator} id="total">=</button>
format the file

2024-01-06 04:14 UTC, sadanandpai commented
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/9b3bd226-324a-4eff-bca7-dd5dd5c08dd8)
No need of having the background around calci and also align the number display

2024-01-06 07:02 UTC, LIZA1608 commented
ok sure

2024-01-06 08:11 UTC, LIZA1608 commented
If more changes are required then please tell??

2024-01-06 11:32 UTC, sadanandpai commented
plz add yourself to contributor list if not present already

2024-01-06 11:35 UTC, LIZA1608 commented
Can you tell me how to do that??

2024-01-06 14:14 UTC, LIZA1608 commented
> plz add yourself to contributor list if not present already

i guess i done please check

2024-01-06 16:17 UTC, merged