basic stopwatch app with vuejs
sadanandpai/frontend-mini-challenges pull request #371
Opened 2024-01-20 10:02 UTC by Shardik04

# Title and Issue number 

Title : Stopwatch with Vuejs

Issue No. : #370 

Code Stack : Vuejs

Close #370

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have updated the Index.html file for my contribution

2024-01-20 15:42 UTC, sadanandpai requested changes

2024-01-20 15:42 UTC, sadanandpai commented on apps/vue/src/challenges/stopwatch/index.vue
> +        <h5 class="flex-center">Stopwatch</h5>
heading is not needed

2024-01-20 15:43 UTC, sadanandpai commented
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/8842510a-4cf1-433c-bdd1-3532393c341a)

contributor icon is broken.

2024-01-21 17:52 UTC, arpansaha13 commented on apps/vue/src/challenges/stopwatch/index.vue
> +<style scoped css="scss">
I think the `css="scss"` property is not required. See if it works without this property.

2024-01-21 17:57 UTC, arpansaha13 commented on apps/vue/src/challenges/stopwatch/index.vue
> +}
You may try computed properties for this function

2024-01-25 09:49 UTC, arpansaha13 requested changes

2024-01-25 09:49 UTC, arpansaha13 commented on apps/vue/src/challenges/stopwatch/index.vue
> +    time.value = { ...time.value };
Please check if the functionality still works if this line is removed

2024-01-30 03:53 UTC, arpansaha13 approved these changes

2024-01-30 06:17 UTC, merged