Color Me Javascript Challenge
sadanandpai/frontend-mini-challenges pull request #479
Opened 2024-08-09 11:44 UTC by X0rD3v1L

Title : Color Me

Code Stack : Vanilla JS

2024-08-10 07:49 UTC, sadanandpai commented
![image](https://github.com/user-attachments/assets/cdd08b9f-a2c7-427e-b96e-d5d0dac791b0)
is this tested

2024-08-10 08:16 UTC, X0rD3v1L commented
I have added a check to load the js once the DOM content is loaded, Can you please check now?

![image](https://github.com/user-attachments/assets/9228360b-7bf1-4373-b7e3-6ad755901de5)

2024-08-12 03:52 UTC, sadanandpai commented
I can see the same problem still.
https://deploy-preview-479--frontend-mini-challenges.netlify.app/javascript/src/challenges/color-me/

2024-08-12 03:56 UTC, sadanandpai requested changes

2024-08-12 03:56 UTC, sadanandpai commented on apps/javascript/src/challenges/color-me/index.js
> +document.addEventListener('DOMContentLoaded', () => {
as we are using defer, do we need DOMContentLoaded?

2024-08-12 03:56 UTC, sadanandpai commented on apps/javascript/src/challenges/color-me/index.html
> +      </div>
This should be a form. The value should be taken when the **Enter** key is pressed

2024-08-12 03:56 UTC, sadanandpai commented on apps/javascript/src/challenges/color-me/index.html
> +    <script src="index.js" defer></script>
move to head section

2024-08-12 03:56 UTC, sadanandpai commented on apps/javascript/src/challenges/color-me/index.html
> +    <title>3x3 Round Grid Color Me</title>
above tags not needed

2024-08-13 12:00 UTC, X0rD3v1L commented
> I can see the same problem still. https://deploy-preview-479--frontend-mini-challenges.netlify.app/javascript/src/challenges/color-me/

type="module" resolved the issue, and removed the defer as modules are automatically deferred.

2024-08-13 13:18 UTC, merged