Food Website [HACTOBER FEST 2023]
sadanandpai/frontend-mini-challenges pull request #85
Opened 2023-10-01 06:23 UTC by apu52

**Describe the project you want to add with tech stack**
This repo contains my project on my Food Website😋. I have made it using HTML,CSS & **JS (mainly)**. It contains a menu card of different cuisines such as Biriyani , Chinese, Paneer Mania, Veg as well as South Indian.🍕 . If you can add new features in the project or in this repos. You can contribute to this open source repository.🤖

**Expected behavior**
Here is my Food website of the resturent names Mr. Chef(ESTD. 2003)🍴 .This website is responsive & it has been made using HTML, CSS, JS. Here are some key features of the website.

- A menu card of different cuisines such as Biriyani , Chienese, Paneer Mania, Veg as well as South Indian.🍕
- A scroll or jump to section to different sections of menu card🥗
- Every dish has it's own rating & prices🥘
- A very unique Add to cart system ( customers can also see the total billing there) 🍟
- Address Saving Option🦑🦐

**Screenshots**

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/114172928/7742ebff-4c6d-47c8-822c-4000a7c5be98)

Additional context (optional )

Please take a review of my PR & merge it   under HACTOBERFEST 2023 .

2023-10-01 06:24 UTC, apu52 commented
@sadanandpai  please take a look in my PR & after reviewing , Please merge it under HACTOBERFERST 2023.

2023-10-01 19:28 UTC, apu52 commented
@sadanandpai please take a look in my PR & after reviewing , Please merge it under HACTOBERFERST 2023.

2023-10-02 07:06 UTC, sadanandpai requested changes

2023-10-02 07:06 UTC, sadanandpai commented on native/machine-coding/Food Website/index.js
Code can be refactored to to keep it maintainable and simple.

- Use array and loop over if needed
- create reusable functions and make calls
- prefer let over var
- add comments wherever necessary

2023-10-11 06:03 UTC, sadanandpai requested changes

2023-10-11 06:03 UTC, sadanandpai commented on native/machine-coding/Food Website/index.html
> +</head>
import the header as done in [counter](https://github.com/sadanandpai/frontend-mini-challenges/blob/main/native/machine-coding/counter/index.html)

Also, remove the other tags

2023-10-11 06:03 UTC, sadanandpai commented on native/machine-coding/Food Website/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
dow we really need font awesome

2023-10-11 06:03 UTC, sadanandpai commented on native/machine-coding/Food Website/index.html
> +    <script src="/index.js" type="module"></script>
move inside head

2023-10-11 06:03 UTC, sadanandpai commented on native/machine-coding/Food Website/index.js
> +    var southIndian=  document.getElementById('south-indian');
use const or let as per the usecase

2023-10-11 06:03 UTC, sadanandpai commented on native/machine-coding/Food Website/style.css
> +@media screen and (max-width : 400px) and (-webkit-min-device-pixel-ratio: 2){
any reason for -webkit-min-device-pixel-ratio: 2

2023-10-26 01:31 UTC, closed without merging