Stopwatch[HACTOBERFEST 2023]
sadanandpai/frontend-mini-challenges pull request #86
Opened 2023-10-01 06:49 UTC by apu52

### Describe the project you want to add with tech stack

Hello Sir👨‍💻 ,I am Arpan Chowdhury, a aspiring Web developer.🤖 Here is the project of the front-end Web Development. We all use the most famous Application in our phone named STOPWATCH

### **Expected behavior**
I have made it using JS & CSS (mainly) .

### Video
https://github.com/apu52/Stopwatch-maker/assets/114172928/2cc065fe-f0bd-4759-9fa9-71d50844f31c

### Additional context (optional )

Please take a review of my PR & merge it under HACTOBERFEST 2023 .

2023-10-01 06:49 UTC, apu52 commented
@sadanandpai please take a look in my PR & after reviewing , Please merge it under HACTOBERFERST 2023.

2023-10-01 19:28 UTC, apu52 commented
@sadanandpai please take a look in my PR & after reviewing , Please merge it under HACTOBERFERST 2023.

2023-10-02 07:10 UTC, apu52 commented
@sadanandpai please take a look in my PR & after reviewing , Please merge it under HACTOBERFERST 2023.

2023-10-02 07:20 UTC, sadanandpai requested changes

2023-10-02 07:20 UTC, sadanandpai commented on native/machine-coding/Stopwatch/Contributors.md
why is this needed

2023-10-02 07:20 UTC, sadanandpai commented on native/machine-coding/Stopwatch/Contributing.md
why is this needed

2023-10-02 07:20 UTC, sadanandpai commented on native/machine-coding/Stopwatch/style.css
> +}
please import the core css as done for other challenges which comes with required styles and avoid modifying HTML and Body styles

2023-10-07 11:46 UTC, apu52 commented
@sadanandpai I have resolved the merge conflicts in Style.css file. Can you please check It??
& merge the PR

2023-10-09 20:09 UTC, apu52 commented
@sadanandpai I have resolved the merge conflicts in Style.css file. Can you please check It??
& merge the PR

2023-10-09 20:27 UTC, apu52 commented
@sadanandpai I have resolved the merge conflicts in Style.css file. Can you please check It??
& merge the PR

2023-10-10 04:19 UTC, apu52 commented
I have deleted those files & have changed the codes . @sadanandpai Can you please take a review & please merge it

2023-10-10 18:05 UTC, sadanandpai requested changes

2023-10-10 18:05 UTC, sadanandpai commented on native/helpers/challenges.js
> +    isNew: true,
why do we need AI chess game details for stop watch challenge

2023-10-10 18:05 UTC, sadanandpai commented on native/machine-coding/Stopwatch/index.html
> +    <link rel="stylesheet" href="style.css" />
please add the required tags as done for other challenges

2023-10-10 18:05 UTC, sadanandpai commented on native/machine-coding/Stopwatch/script.js
> +let lapsItems = document.querySelector(".laps-items");
use const for not reassigned variables

2023-10-10 18:05 UTC, sadanandpai commented on native/machine-coding/Stopwatch/style.css
> +}
import the core styles. 
And do not add new fonts.
No need to add * rule set

2023-10-11 05:58 UTC, sadanandpai requested changes

2023-10-11 05:58 UTC, sadanandpai commented on native/machine-coding/Stopwatch/index.html
> +    <script src="script.js"></script>
move script to head with defer

2023-10-11 05:58 UTC, sadanandpai commented on native/machine-coding/Stopwatch/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Aclonica&display=swap');
do not add new fonts

2023-10-26 01:32 UTC, closed without merging